### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shenxiangzhuang** [shenxiangzhuang/beer#42]
# The roadmap of project beer!

## Problem sets
- [ ] #105
- [ ] [概率破玄機 統計解迷離](https://github.com/shenxiangzhuang/beer/milestone/2)
- [ ] Everywhere(Collect from wild :)

## Industrial Application in real world
- [ ] Spot
- [ ] DS: https://datahonor.com/blog/2024/08/21/ds/
